name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build -c Release --filter "FullyQualifiedName!~Spot.E2E"
      - name: Cache Playwright browsers
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('tests/e2e/e2e.csproj') }}
      - name: Playwright install (manual trigger)
        if: ${{ false }}
        run: |
          npx playwright install --with-deps
          dotnet test tests/e2e/e2e.csproj --no-build -c Release
